#pragma once

#define IRA_WIFI_SSID "YOUR_WIFI_SSID"
#define IRA_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define IRA_SERVER_HOST "YOUR_SERVER_HOST"
#define IRA_SERVER_PORT 8765
#define IRA_SERVER_PATH "/"
